
version: 1

topics:
  demo_metric:
    schema:
      int_value: int
      float_value: float
      label: string

metrics:
  demo_metric:
    type: test
    description: Demo metric.
    query_string: |
      SELECT float_value FROM demo_metric
    template_type: system
    template: scalar


metrics sets:
  default:  
    metrics:
      - demo_metric
